// NAVIGATION
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const SET_LOADING = 'SET_LOADING';

// USER
export const GET_USER_INFO = 'GET_USER_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const GET_USER_BALANCES = 'GET_USER_BALANCES';
export const FETCH_USER_BALANCES = 'FETCH_USER_BALANCES';
export const SET_USER_INFO = 'SET_USER_INFO';
export const REQUEST_ACTIVATION = 'REQUEST_ACTIVATION';
export const FETCH_ACTIVATION_REQUESTS = 'FETCH_ACTIVATION_REQUESTS';
export const SET_REQUEST_LIST = 'SET_REQUEST_LIST';
export const ACTIVATE_USER = 'ACTIVATE_USER';
export const DEACTIVATE_USER = 'DEACTIVATE_USER';
export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const SET_USER_LIST = 'SET_USER_LIST';
export const FETCH_ACTIVE_LIST = 'FETCH_ACTIVE_LIST';
export const SET_ACTIVE_LIST = 'SET_ACTIVE_LIST';
export const SEND_COCO = 'SEND_COCO';

// ETHEREUM
export const SET_WEB_INSTANCE = 'SET_WEB_INSTANCE';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_COMMUNITY_PROTOCOL = 'SET_COMMUNITY_PROTOCOL';
