// NAVIGATION
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const SET_LOADING = 'SET_LOADING';

// USER
export const GET_USER_INFO = 'GET_USER_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const GET_USER_BALANCES = 'GET_USER_BALANCES';
export const FETCH_USER_BALANCES = 'FETCH_USER_BALANCES';
export const SET_USER_INFO = 'SET_USER_INFO';

// ETHEREUM
export const SET_WEB_INSTANCE = 'SET_WEB_INSTANCE';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_COMMUNITY_PROTOCOL = 'SET_COMMUNITY_PROTOCOL';
